#ifndef ERR_CODE_H__
#define ERR_CODE_H__

typedef enum
{
	CODE_ERR = -1,
	CODE_OK = 0,
	CODE_NOT_RESPONSE,
	CODE_DATA_ARRAY,
	CODE_TIMEOUT,
	CODE_NOT_FOUND_DEVICE,
	CODE_NOT_FOUND_GROUP,
	CODE_NOT_FOUND_SCENE,
	CODE_NOT_FOUND_RULE,
	CODE_NOT_FOUND_ROOM,
	CODE_FORMAT_ERROR,
	CODE_DATABASE_ERROR,
	CODE_MEMORY_ERROR,
	CODE_FILE_ERROR,
	CODE_EXIT,
	CODE_REBOOT,
	CODE_FACTORY,
	CODE_OTA_ERROR,
	CODE_OTA_DATA_ERROR,
	CODE_OTA_CHECK_CRC_ERROR,

    CODE_FLASH_ERR,
} ErrorCode;

#endif